//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace BDEditor
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BDModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BDModelContainer object using the connection string found in the 'BDModelContainer' section of the application configuration file.
        /// </summary>
        public BDModelContainer() : base("name=BDModelContainer", "BDModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BDModelContainer object.
        /// </summary>
        public BDModelContainer(string connectionString) : base(connectionString, "BDModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BDModelContainer object.
        /// </summary>
        public BDModelContainer(EntityConnection connection) : base(connection, "BDModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BDCategory> BDCategories
        {
            get
            {
                if ((_BDCategories == null))
                {
                    _BDCategories = base.CreateObjectSet<BDCategory>("BDCategories");
                }
                return _BDCategories;
            }
        }
        private ObjectSet<BDCategory> _BDCategories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BDSection> BDSections
        {
            get
            {
                if ((_BDSections == null))
                {
                    _BDSections = base.CreateObjectSet<BDSection>("BDSections");
                }
                return _BDSections;
            }
        }
        private ObjectSet<BDSection> _BDSections;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BDSubCategory> BDSubCategories
        {
            get
            {
                if ((_BDSubCategories == null))
                {
                    _BDSubCategories = base.CreateObjectSet<BDSubCategory>("BDSubCategories");
                }
                return _BDSubCategories;
            }
        }
        private ObjectSet<BDSubCategory> _BDSubCategories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BDQueueEntry> BDQueueEntries
        {
            get
            {
                if ((_BDQueueEntries == null))
                {
                    _BDQueueEntries = base.CreateObjectSet<BDQueueEntry>("BDQueueEntries");
                }
                return _BDQueueEntries;
            }
        }
        private ObjectSet<BDQueueEntry> _BDQueueEntries;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BDLinkedNote> BDLinkedNotes
        {
            get
            {
                if ((_BDLinkedNotes == null))
                {
                    _BDLinkedNotes = base.CreateObjectSet<BDLinkedNote>("BDLinkedNotes");
                }
                return _BDLinkedNotes;
            }
        }
        private ObjectSet<BDLinkedNote> _BDLinkedNotes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BDCategories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBDCategories(BDCategory bDCategory)
        {
            base.AddObject("BDCategories", bDCategory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BDSections EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBDSections(BDSection bDSection)
        {
            base.AddObject("BDSections", bDSection);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BDSubCategories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBDSubCategories(BDSubCategory bDSubCategory)
        {
            base.AddObject("BDSubCategories", bDSubCategory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BDQueueEntries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBDQueueEntries(BDQueueEntry bDQueueEntry)
        {
            base.AddObject("BDQueueEntries", bDQueueEntry);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BDLinkedNotes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBDLinkedNotes(BDLinkedNote bDLinkedNote)
        {
            base.AddObject("BDLinkedNotes", bDLinkedNote);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BDModel", Name="BDCategory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BDCategory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BDCategory object.
        /// </summary>
        /// <param name="uuid">Initial value of the uuid property.</param>
        public static BDCategory CreateBDCategory(global::System.Guid uuid)
        {
            BDCategory bDCategory = new BDCategory();
            bDCategory.uuid = uuid;
            return bDCategory;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid uuid
        {
            get
            {
                return _uuid;
            }
            set
            {
                if (_uuid != value)
                {
                    OnuuidChanging(value);
                    ReportPropertyChanging("uuid");
                    _uuid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("uuid");
                    OnuuidChanged();
                }
            }
        }
        private global::System.Guid _uuid;
        partial void OnuuidChanging(global::System.Guid value);
        partial void OnuuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> sectionId
        {
            get
            {
                return _sectionId;
            }
            set
            {
                OnsectionIdChanging(value);
                ReportPropertyChanging("sectionId");
                _sectionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sectionId");
                OnsectionIdChanged();
            }
        }
        private Nullable<global::System.Guid> _sectionId;
        partial void OnsectionIdChanging(Nullable<global::System.Guid> value);
        partial void OnsectionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> createdBy
        {
            get
            {
                return _createdBy;
            }
            set
            {
                OncreatedByChanging(value);
                ReportPropertyChanging("createdBy");
                _createdBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdBy");
                OncreatedByChanged();
            }
        }
        private Nullable<global::System.Guid> _createdBy;
        partial void OncreatedByChanging(Nullable<global::System.Guid> value);
        partial void OncreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createdDate
        {
            get
            {
                return _createdDate;
            }
            set
            {
                OncreatedDateChanging(value);
                ReportPropertyChanging("createdDate");
                _createdDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdDate");
                OncreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _createdDate;
        partial void OncreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OncreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> modifiedBy
        {
            get
            {
                return _modifiedBy;
            }
            set
            {
                OnmodifiedByChanging(value);
                ReportPropertyChanging("modifiedBy");
                _modifiedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modifiedBy");
                OnmodifiedByChanged();
            }
        }
        private Nullable<global::System.Guid> _modifiedBy;
        partial void OnmodifiedByChanging(Nullable<global::System.Guid> value);
        partial void OnmodifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> modifiedDate
        {
            get
            {
                return _modifiedDate;
            }
            set
            {
                OnmodifiedDateChanging(value);
                ReportPropertyChanging("modifiedDate");
                _modifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modifiedDate");
                OnmodifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _modifiedDate;
        partial void OnmodifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnmodifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 schemaVersion
        {
            get
            {
                return _schemaVersion;
            }
            set
            {
                OnschemaVersionChanging(value);
                ReportPropertyChanging("schemaVersion");
                _schemaVersion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("schemaVersion");
                OnschemaVersionChanged();
            }
        }
        private global::System.Int16 _schemaVersion = 0;
        partial void OnschemaVersionChanging(global::System.Int16 value);
        partial void OnschemaVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean deprecated
        {
            get
            {
                return _deprecated;
            }
            set
            {
                OndeprecatedChanging(value);
                ReportPropertyChanging("deprecated");
                _deprecated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("deprecated");
                OndeprecatedChanged();
            }
        }
        private global::System.Boolean _deprecated = false;
        partial void OndeprecatedChanging(global::System.Boolean value);
        partial void OndeprecatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> inUseBy
        {
            get
            {
                return _inUseBy;
            }
            set
            {
                OninUseByChanging(value);
                ReportPropertyChanging("inUseBy");
                _inUseBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("inUseBy");
                OninUseByChanged();
            }
        }
        private Nullable<global::System.Guid> _inUseBy;
        partial void OninUseByChanging(Nullable<global::System.Guid> value);
        partial void OninUseByChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BDModel", Name="BDLinkedNote")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BDLinkedNote : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BDLinkedNote object.
        /// </summary>
        /// <param name="uuid">Initial value of the uuid property.</param>
        /// <param name="storageKey">Initial value of the storageKey property.</param>
        public static BDLinkedNote CreateBDLinkedNote(global::System.Guid uuid, global::System.String storageKey)
        {
            BDLinkedNote bDLinkedNote = new BDLinkedNote();
            bDLinkedNote.uuid = uuid;
            bDLinkedNote.storageKey = storageKey;
            return bDLinkedNote;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid uuid
        {
            get
            {
                return _uuid;
            }
            set
            {
                if (_uuid != value)
                {
                    OnuuidChanging(value);
                    ReportPropertyChanging("uuid");
                    _uuid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("uuid");
                    OnuuidChanged();
                }
            }
        }
        private global::System.Guid _uuid;
        partial void OnuuidChanging(global::System.Guid value);
        partial void OnuuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> createdBy
        {
            get
            {
                return _createdBy;
            }
            set
            {
                OncreatedByChanging(value);
                ReportPropertyChanging("createdBy");
                _createdBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdBy");
                OncreatedByChanged();
            }
        }
        private Nullable<global::System.Guid> _createdBy;
        partial void OncreatedByChanging(Nullable<global::System.Guid> value);
        partial void OncreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createdDate
        {
            get
            {
                return _createdDate;
            }
            set
            {
                OncreatedDateChanging(value);
                ReportPropertyChanging("createdDate");
                _createdDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdDate");
                OncreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _createdDate;
        partial void OncreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OncreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> modifiedBy
        {
            get
            {
                return _modifiedBy;
            }
            set
            {
                OnmodifiedByChanging(value);
                ReportPropertyChanging("modifiedBy");
                _modifiedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modifiedBy");
                OnmodifiedByChanged();
            }
        }
        private Nullable<global::System.Guid> _modifiedBy;
        partial void OnmodifiedByChanging(Nullable<global::System.Guid> value);
        partial void OnmodifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> modifiedDate
        {
            get
            {
                return _modifiedDate;
            }
            set
            {
                OnmodifiedDateChanging(value);
                ReportPropertyChanging("modifiedDate");
                _modifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modifiedDate");
                OnmodifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _modifiedDate;
        partial void OnmodifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnmodifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 schemaVersion
        {
            get
            {
                return _schemaVersion;
            }
            set
            {
                OnschemaVersionChanging(value);
                ReportPropertyChanging("schemaVersion");
                _schemaVersion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("schemaVersion");
                OnschemaVersionChanged();
            }
        }
        private global::System.Int16 _schemaVersion = 0;
        partial void OnschemaVersionChanging(global::System.Int16 value);
        partial void OnschemaVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean deprecated
        {
            get
            {
                return _deprecated;
            }
            set
            {
                OndeprecatedChanging(value);
                ReportPropertyChanging("deprecated");
                _deprecated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("deprecated");
                OndeprecatedChanged();
            }
        }
        private global::System.Boolean _deprecated = false;
        partial void OndeprecatedChanging(global::System.Boolean value);
        partial void OndeprecatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> inUseBy
        {
            get
            {
                return _inUseBy;
            }
            set
            {
                OninUseByChanging(value);
                ReportPropertyChanging("inUseBy");
                _inUseBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("inUseBy");
                OninUseByChanged();
            }
        }
        private Nullable<global::System.Guid> _inUseBy;
        partial void OninUseByChanging(Nullable<global::System.Guid> value);
        partial void OninUseByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String documentText
        {
            get
            {
                return _documentText;
            }
            set
            {
                OndocumentTextChanging(value);
                ReportPropertyChanging("documentText");
                _documentText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("documentText");
                OndocumentTextChanged();
            }
        }
        private global::System.String _documentText;
        partial void OndocumentTextChanging(global::System.String value);
        partial void OndocumentTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String storageKey
        {
            get
            {
                return _storageKey;
            }
            set
            {
                OnstorageKeyChanging(value);
                ReportPropertyChanging("storageKey");
                _storageKey = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("storageKey");
                OnstorageKeyChanged();
            }
        }
        private global::System.String _storageKey;
        partial void OnstorageKeyChanging(global::System.String value);
        partial void OnstorageKeyChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BDModel", Name="BDQueueEntry")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BDQueueEntry : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BDQueueEntry object.
        /// </summary>
        /// <param name="uuid">Initial value of the uuid property.</param>
        /// <param name="objectUuid">Initial value of the objectUuid property.</param>
        /// <param name="objectEntityName">Initial value of the objectEntityName property.</param>
        public static BDQueueEntry CreateBDQueueEntry(global::System.Guid uuid, global::System.Guid objectUuid, global::System.String objectEntityName)
        {
            BDQueueEntry bDQueueEntry = new BDQueueEntry();
            bDQueueEntry.uuid = uuid;
            bDQueueEntry.objectUuid = objectUuid;
            bDQueueEntry.objectEntityName = objectEntityName;
            return bDQueueEntry;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid uuid
        {
            get
            {
                return _uuid;
            }
            set
            {
                if (_uuid != value)
                {
                    OnuuidChanging(value);
                    ReportPropertyChanging("uuid");
                    _uuid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("uuid");
                    OnuuidChanged();
                }
            }
        }
        private global::System.Guid _uuid;
        partial void OnuuidChanging(global::System.Guid value);
        partial void OnuuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> timestamp
        {
            get
            {
                return _timestamp;
            }
            set
            {
                OntimestampChanging(value);
                ReportPropertyChanging("timestamp");
                _timestamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("timestamp");
                OntimestampChanged();
            }
        }
        private Nullable<global::System.DateTime> _timestamp;
        partial void OntimestampChanging(Nullable<global::System.DateTime> value);
        partial void OntimestampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid objectUuid
        {
            get
            {
                return _objectUuid;
            }
            set
            {
                OnobjectUuidChanging(value);
                ReportPropertyChanging("objectUuid");
                _objectUuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("objectUuid");
                OnobjectUuidChanged();
            }
        }
        private global::System.Guid _objectUuid;
        partial void OnobjectUuidChanging(global::System.Guid value);
        partial void OnobjectUuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String objectEntityName
        {
            get
            {
                return _objectEntityName;
            }
            set
            {
                OnobjectEntityNameChanging(value);
                ReportPropertyChanging("objectEntityName");
                _objectEntityName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("objectEntityName");
                OnobjectEntityNameChanged();
            }
        }
        private global::System.String _objectEntityName;
        partial void OnobjectEntityNameChanging(global::System.String value);
        partial void OnobjectEntityNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 action
        {
            get
            {
                return _action;
            }
            set
            {
                OnactionChanging(value);
                ReportPropertyChanging("action");
                _action = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("action");
                OnactionChanged();
            }
        }
        private global::System.Int16 _action = 0;
        partial void OnactionChanging(global::System.Int16 value);
        partial void OnactionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BDModel", Name="BDSection")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BDSection : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BDSection object.
        /// </summary>
        /// <param name="uuid">Initial value of the uuid property.</param>
        public static BDSection CreateBDSection(global::System.Guid uuid)
        {
            BDSection bDSection = new BDSection();
            bDSection.uuid = uuid;
            return bDSection;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid uuid
        {
            get
            {
                return _uuid;
            }
            set
            {
                if (_uuid != value)
                {
                    OnuuidChanging(value);
                    ReportPropertyChanging("uuid");
                    _uuid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("uuid");
                    OnuuidChanged();
                }
            }
        }
        private global::System.Guid _uuid;
        partial void OnuuidChanging(global::System.Guid value);
        partial void OnuuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> createdBy
        {
            get
            {
                return _createdBy;
            }
            set
            {
                OncreatedByChanging(value);
                ReportPropertyChanging("createdBy");
                _createdBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdBy");
                OncreatedByChanged();
            }
        }
        private Nullable<global::System.Guid> _createdBy;
        partial void OncreatedByChanging(Nullable<global::System.Guid> value);
        partial void OncreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createdDate
        {
            get
            {
                return _createdDate;
            }
            set
            {
                OncreatedDateChanging(value);
                ReportPropertyChanging("createdDate");
                _createdDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdDate");
                OncreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _createdDate;
        partial void OncreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OncreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> modifiedBy
        {
            get
            {
                return _modifiedBy;
            }
            set
            {
                OnmodifiedByChanging(value);
                ReportPropertyChanging("modifiedBy");
                _modifiedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modifiedBy");
                OnmodifiedByChanged();
            }
        }
        private Nullable<global::System.Guid> _modifiedBy;
        partial void OnmodifiedByChanging(Nullable<global::System.Guid> value);
        partial void OnmodifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> modifiedDate
        {
            get
            {
                return _modifiedDate;
            }
            set
            {
                OnmodifiedDateChanging(value);
                ReportPropertyChanging("modifiedDate");
                _modifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modifiedDate");
                OnmodifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _modifiedDate;
        partial void OnmodifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnmodifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 schemaVersion
        {
            get
            {
                return _schemaVersion;
            }
            set
            {
                OnschemaVersionChanging(value);
                ReportPropertyChanging("schemaVersion");
                _schemaVersion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("schemaVersion");
                OnschemaVersionChanged();
            }
        }
        private global::System.Int16 _schemaVersion = 0;
        partial void OnschemaVersionChanging(global::System.Int16 value);
        partial void OnschemaVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean deprecated
        {
            get
            {
                return _deprecated;
            }
            set
            {
                OndeprecatedChanging(value);
                ReportPropertyChanging("deprecated");
                _deprecated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("deprecated");
                OndeprecatedChanged();
            }
        }
        private global::System.Boolean _deprecated = false;
        partial void OndeprecatedChanging(global::System.Boolean value);
        partial void OndeprecatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> inUseBy
        {
            get
            {
                return _inUseBy;
            }
            set
            {
                OninUseByChanging(value);
                ReportPropertyChanging("inUseBy");
                _inUseBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("inUseBy");
                OninUseByChanged();
            }
        }
        private Nullable<global::System.Guid> _inUseBy;
        partial void OninUseByChanging(Nullable<global::System.Guid> value);
        partial void OninUseByChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BDModel", Name="BDSubCategory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BDSubCategory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BDSubCategory object.
        /// </summary>
        /// <param name="uuid">Initial value of the uuid property.</param>
        public static BDSubCategory CreateBDSubCategory(global::System.Guid uuid)
        {
            BDSubCategory bDSubCategory = new BDSubCategory();
            bDSubCategory.uuid = uuid;
            return bDSubCategory;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid uuid
        {
            get
            {
                return _uuid;
            }
            set
            {
                if (_uuid != value)
                {
                    OnuuidChanging(value);
                    ReportPropertyChanging("uuid");
                    _uuid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("uuid");
                    OnuuidChanged();
                }
            }
        }
        private global::System.Guid _uuid;
        partial void OnuuidChanging(global::System.Guid value);
        partial void OnuuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> categoryId
        {
            get
            {
                return _categoryId;
            }
            set
            {
                OncategoryIdChanging(value);
                ReportPropertyChanging("categoryId");
                _categoryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("categoryId");
                OncategoryIdChanged();
            }
        }
        private Nullable<global::System.Guid> _categoryId;
        partial void OncategoryIdChanging(Nullable<global::System.Guid> value);
        partial void OncategoryIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> createdBy
        {
            get
            {
                return _createdBy;
            }
            set
            {
                OncreatedByChanging(value);
                ReportPropertyChanging("createdBy");
                _createdBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdBy");
                OncreatedByChanged();
            }
        }
        private Nullable<global::System.Guid> _createdBy;
        partial void OncreatedByChanging(Nullable<global::System.Guid> value);
        partial void OncreatedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createdDate
        {
            get
            {
                return _createdDate;
            }
            set
            {
                OncreatedDateChanging(value);
                ReportPropertyChanging("createdDate");
                _createdDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdDate");
                OncreatedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _createdDate;
        partial void OncreatedDateChanging(Nullable<global::System.DateTime> value);
        partial void OncreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> modifiedBy
        {
            get
            {
                return _modifiedBy;
            }
            set
            {
                OnmodifiedByChanging(value);
                ReportPropertyChanging("modifiedBy");
                _modifiedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modifiedBy");
                OnmodifiedByChanged();
            }
        }
        private Nullable<global::System.Guid> _modifiedBy;
        partial void OnmodifiedByChanging(Nullable<global::System.Guid> value);
        partial void OnmodifiedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> modifiedDate
        {
            get
            {
                return _modifiedDate;
            }
            set
            {
                OnmodifiedDateChanging(value);
                ReportPropertyChanging("modifiedDate");
                _modifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modifiedDate");
                OnmodifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _modifiedDate;
        partial void OnmodifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnmodifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 schemaVersion
        {
            get
            {
                return _schemaVersion;
            }
            set
            {
                OnschemaVersionChanging(value);
                ReportPropertyChanging("schemaVersion");
                _schemaVersion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("schemaVersion");
                OnschemaVersionChanged();
            }
        }
        private global::System.Int16 _schemaVersion = 0;
        partial void OnschemaVersionChanging(global::System.Int16 value);
        partial void OnschemaVersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean deprecated
        {
            get
            {
                return _deprecated;
            }
            set
            {
                OndeprecatedChanging(value);
                ReportPropertyChanging("deprecated");
                _deprecated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("deprecated");
                OndeprecatedChanged();
            }
        }
        private global::System.Boolean _deprecated = false;
        partial void OndeprecatedChanging(global::System.Boolean value);
        partial void OndeprecatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> inUseBy
        {
            get
            {
                return _inUseBy;
            }
            set
            {
                OninUseByChanging(value);
                ReportPropertyChanging("inUseBy");
                _inUseBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("inUseBy");
                OninUseByChanged();
            }
        }
        private Nullable<global::System.Guid> _inUseBy;
        partial void OninUseByChanging(Nullable<global::System.Guid> value);
        partial void OninUseByChanged();

        #endregion
    
    }

    #endregion
    
}
